### ISSUE TITLE
Missing votes

### ISSUE THREAD

**Issue by JayBraker** [HowTheyVote/epvotes#898]
Hi, really cool project.

I will look forward to using this, right now I utilize my own scraper.
When looking for RCVs I realized that this Pattern 
https://github.com/HowTheyVote/epvotes/blob/005c733b24ddf6cd60143362922f97024badf388/scrapers/ep_votes/scrapers.py#L283

probably isn't enough: It seems the available documents alternate between `PV-9-2021-03-09-RCV_EN.xml` and `PV-9-2021-03-09-RCV_FR.xml`.
I am unsure whether there will also be documents exclusive in any other language (as hinted in the header of https://www.europarl.europa.eu/doceo/document/PV-9-2022-01-19-RCV_FR.html)

Between 2020-01-13 and 2021-12-16 I could only find documents with the appendix FR.
From 2022-01-19 to 2022-01-19 I found documents for BG as well as EN and from there on only EN till today.

Can you confirm this observation?

**Comment by JayBraker** [comment]
Wait, not an issue? FR seems to be always available whilst EN is not..

Sorry for the bother, my bad.

**Comment by linusha** [comment]
> Wait, not an issue? FR seems to be always available whilst EN is not..

Yes, this is what we thought in the end as well. No worries!

In the case you are using this project for scraping only, you should be able to retrieve all votes in the database. However, please be aware that in the front-end, not all votes are currently displayed and some internal flags (most notably the flag if a vote is the final vote on a matter) are not always correct. This is because the matching in the PHP code is heuristics based, and that heuristic is not super reliable. We are working on a new version that does not have this problem, but we cannot give a reliable ETA right now. We will somehow make it known here when we have it!

Cheers!
